### ISSUE TITLE
Question:  Will this help maintain relationship integrity?

### ISSUE THREAD

**Issue by debstone** [bnadler/Append-Features-With-Attachments#6]
Can this code be used to maintain a primary key (Global ID) to foreign key (GUID) relationship as data is brought in from AGOL to a locally stored copy of the same database?

We are using Collector to collect field data for a map in AGOL, but we need to maintain a locally stored copy that we can do some minor modifications on and use for report generating.  Our geodatabase has three layers of relationships (Point feature class--> Polygon feature class --> Table), with each primary key being a GlobalID (so that it is automatically generated and unique as we have a dozen daily users) and I need to update the new data from AGOL to the local copy weekly.  Obviously, when I Append the new data, the GlobalID changes but the associated GUID in the related table doesn't change and the relationship between the two files is destroyed.  I can't simply overwrite the locally stored copy because we will have modified that data and don't want to repeat all that editing.

I'm new to Python, so I'm not well versed enough to see if this code can be used to maintain other relationships besides that with attachments...

**Comment by bnadler** [comment]
Yes, this can be modified to update other relationships as well. It would not be too complicated since the GlobalID lookup table can be reused.

There is another option worth looking into that *may* render this script obsolete.
There is a checkbox for a geoprocessing environment setting in ArcGIS Pro called something like "Preserve GlobalID".
In theory, the  Append tool (with this setting  enabled) would carry over the GlobalID from the AGOL DB to the appended DB, thus keeping All GlobalID based relationships intact.

Either way, good luck and have fun.

Ben Nadler | Esri Professional Services |
Technical Analyst – Utilities, Telecom, & Energy
 [cid:storage_extSdCard_DCIM_Camera_image002]
C: 303.884.9323 | O: 303.449.7779 X8278
Sent from my phone


-------- Original message --------

**Comment by debstone** [comment]
Thanks for your quick reply!  I really appreciate your help, especially as I am just learning Python.

Would I need to alter more than the "REL_GLOBALID" on lines 115 and 121 to the name of the corresponding field in the new update file (i.e. the fc or tfc variable on line 107/108)?  Also, would I only need to make two other versions of this tool, one for the Point-> Polygon relationship, and another for the Polygon-> Table relationship (we also have attachments on the Point file)?

We don't really use ArcGIS Pro but I will look into that option as well.  Thanks again and have a great day!

**Comment by bnadler** [comment]
You are on the right track.

You  would want to structure your script to append the three feature classes and attachments first and have 3 GUID dictionaries, then for each feature class and attachment table run the GUID update with the appropriate field name and GUID dictionary

Perhaps break out the GUID update procedure (lines 114-125) into a separate function that accepts field name and GUID dictionary as parameters
That way you can call it multiple times (once for each foreign key field in the FC)

Sincerely,


[cid:image001.png@01D007E6.EAD9F710]Ben Nadler | Esri Professional Services | Technical Analyst | Utilities, Telecom, & Energy

O: 303.449.7779 ext. 8278 | C: 303.884.9323 | E: bnadler@esri.com<mailto:bnadler@esri.com> | esri.com/services<www.esri.com/services>
